# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Grant Leadbetter"
description: > # this means to ignore newlines until "email:"
   Software Developer

email: grant_leadbetter@live.co.uk
#blog logo
logo: "/assets/images/pineapple.png"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Grant Leadbetter'
author: 'Grant Leadbetter'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://grantlyk.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/koangrant
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/Grantlyk
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
